### ISSUE TITLE
[BUG] 资源下载链接包名地址 出现#字符 但是Http下载不支持 

### ISSUE THREAD

**Issue by Starkappa** [AIO-GAME/Unity.Asset.CLI#35]
**描述问题 - Describe the bug**
> _(对问题的清晰而简洁的描述)_
> _(A clear and concise description of what the bug is.)
资源下载链接包名地址 出现#字符 但是Http下载不支持 
**重现步骤 - To Reproduce**
>_( 重现行为的步骤)_
> _(Steps to reproduce the behavior)_
1. 收集器路径名称设置#字符或者资源名包含#字符
2. 打包完成后开启远端模式 
3. 开启下载 则会出现报错

**期望行为 - Expected behavior** [ignore]
> _(对你期望发生的情况的清晰而简洁的描述)_
> _(A clear and concise description of what you expected to happen.)_
将#字符自动替换为http支持的路径字符

**Comment by xinansky** [comment]
此问题应该考虑资源服务器对路径的支持
目前需要配置对一些特殊字符进行编码
下版本会支持自动将#字符等其他特殊字符修改为_
